### PR TITLE
Wait for transaction commit before pushing tasks

### PR DESCRIPTION
**Pull request by erikh360**

### CODE REVIEW

**Comment by smn** [comment]
Feels like quite a low level change to be making without having a test to confirm this fixes an issue?

**Comment by erikh360** [comment]
@smn Please have a look at my tests, they will still need to move to a more appropriate place and I am still figuring out why they are not working with other tests. I just want to know if I'm wasting my time. The way I see it the new code removes the race condition so I just make sure it's working, no need to test for the race condition.

**Comment by smn** [comment]
Hm this is tricky, I agree but I'm not sure how we're going to land this upstream :/

**Comment by erikh360** [comment]
@smn @jerith Please have a look. The test fails if I revert my change because the objects is not yet in the DB.

**Comment by smn** [comment]
:+1: from me @erikh360, let's also submit upstream as it'll have to go through review there too before getting merged in to the main release.

**Pull request merged**
